### ISSUE TITLE
Pay for Heroku Dyno?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/api#7]
Given that Heroku's (_free_) dynos go to [sleep mode](https://www.youtube.com/watch?v=dQj0zlnZqvU) after a minute of inactivity and then take a few seconds to boot we should consider _paying_ for a non-sleeping dyno for the API so there's no lag (_start up time_) for people visiting the app.

Thankfully, Heroku recently updated their prices: https://blog.heroku.com/archives/2015/6/15/dynos-pricing-ga 

> "_Hobby dynos have **512MB of RAM**, **never sleep**, and are only **$7** per dyno per **month**_"

What do you think?

**Comment by iteles** [comment]
It seems like we'll only need 1 hobby dyno for the next couple of months and that we'll have to pay for non-free dynos when we start to scale anyway.
At $7 a month I think it makes sense to keep us from having to decipher whether the lag is in our code or the dyno waking up (or worse, assuming the issue is the dyno when actually it's in the code) [this summer](https://github.com/dwyl/summer-2015)

**Comment by iteles** [comment]
@nelsonic What do _you_ think?

**Comment by nelsonic** [comment]
Seems like a no-brainer. 👍
